[package]
name = "kifi"
version = "0.2.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.23", features = ["derive"] }
serde = "1.0.186"
serde_cbor = "0.11.2"
serde_derive = "1.0.188"
